apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: myapp-placement
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      name: myapp
      version: v1
  policy:
    placementType: PickAll
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      unavailablePeriodSeconds: 60
